### ISSUE TITLE
Unable to find devices

### ISSUE THREAD

**Issue by nithrous** [ybenannoune/YeelightController#3]
Hi,

I have Yeelight color bulbs that works perfectly via native app or google home, but I can't find them by this app. I tried to switch my firewall off but it is still not working.

Any ideas?

**Comment by ybenannoune** [comment]
Hi,

Hum, your color bulbs are in developer mode? (this allow your bulbs to be visible on the network)
Your PC is on the same network? Try to display the IP used by the APP to check if it's the good one.

**Comment by nithrous** [comment]
@ybenannoune , thanks! My bulbs were not in developer mode. Now they works!
